---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build-1.12
    pull: always
    image: golang:1.12
    commands:
      - go test -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    when:
      event:
        exclude:
          - tag

  - name: build-1.13
    pull: always
    image: golang:1.13
    commands:
      - go test -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    when:
      event:
        exclude:
          - tag

  - name: build-1.14
    pull: always
    image: golang:1.14
    commands:
      - go test -v ./...
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    when:
      event:
        exclude:
          - tag
